-- 產品管理：分類與產品表（維持舊版 db-bak 原架構，僅改 ENGINE/CHARSET）
-- 對應：pro_classlist / pro_product（台灣）、_sg（新加坡）、_mm（緬甸）

SET NAMES utf8mb4;

-- ---------------------------------------------------------------------------
-- 台灣 分類表 pro_classlist
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_classlist` (
  `classlistID` bigint(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `folderName` varchar(255) DEFAULT NULL,
  `classname` varchar(255) DEFAULT NULL,
  `classseries` varchar(255) DEFAULT NULL,
  `classmaster` bigint(16) UNSIGNED DEFAULT NULL,
  `chk_assembly` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `profile` longtext,
  `price` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `item` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `classordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `chkdel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `onTop` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `pic` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`classlistID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------------
-- 台灣 產品表 pro_product
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_product` (
  `productID` bigint(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `color_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `size_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `qty_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `color` text,
  `size` text,
  `qty` text,
  `youtube` varchar(255) DEFAULT NULL,
  `weight` varchar(255) DEFAULT NULL,
  `stock` varchar(255) DEFAULT NULL,
  `chk_stock` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `classID` bigint(16) UNSIGNED DEFAULT NULL,
  `productname` longtext,
  `productseries` varchar(255) DEFAULT NULL,
  `providerseries` varchar(255) DEFAULT NULL,
  `bonus` bigint(16) UNSIGNED DEFAULT 0,
  `productsimpleprofile` text,
  `productprofile` longtext,
  `productprofile1` longtext,
  `productprofile2` longtext,
  `usermanual` varchar(255) DEFAULT NULL,
  `auction_startprice` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_unit` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_start_yy` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_start_mm` int(4) UNSIGNED DEFAULT NULL,
  `auction_start_dd` int(5) UNSIGNED DEFAULT NULL,
  `auction_end_yy` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_end_mm` int(4) UNSIGNED DEFAULT NULL,
  `auction_end_dd` int(5) UNSIGNED DEFAULT NULL,
  `auction_ship_price` bigint(16) UNSIGNED DEFAULT NULL,
  `marketprice` varchar(255) DEFAULT NULL,
  `memberprice` varchar(255) DEFAULT NULL,
  `providerprice` varchar(255) DEFAULT NULL,
  `bonusprice` varchar(255) DEFAULT NULL,
  `bonuspriceSel` varchar(255) DEFAULT NULL,
  `bonuspriceA` varchar(255) DEFAULT NULL,
  `bonuspriceB` varchar(255) DEFAULT NULL,
  `bonuspriceC` varchar(255) DEFAULT NULL,
  `bonuspriceA_percent` varchar(255) DEFAULT NULL,
  `bonuspriceA_Sel` varchar(255) DEFAULT NULL,
  `bonuspriceB_Plus` varchar(255) DEFAULT NULL,
  `chk_hot` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_auction` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_special` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_limit` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_assembly` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `product_s_gif` varchar(255) DEFAULT NULL,
  `product_s_1_gif` varchar(255) DEFAULT NULL,
  `product_s_2_gif` varchar(255) DEFAULT NULL,
  `product_l_gif` varchar(255) DEFAULT NULL,
  `product_large_gif` varchar(255) DEFAULT NULL,
  `product_special_gif` varchar(255) DEFAULT NULL,
  `productnum` bigint(16) UNSIGNED DEFAULT 0,
  `productordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `posttime` datetime DEFAULT NULL,
  `wholeseries` varchar(255) DEFAULT NULL,
  `limit_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `hot_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `special_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `factory_email` varchar(255) DEFAULT NULL,
  `click` bigint(24) UNSIGNED NOT NULL DEFAULT 0,
  `safenum` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `colorsize` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `letterSearch` varchar(255) DEFAULT NULL,
  `languageSearch` varchar(255) DEFAULT NULL,
  `shopNum` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `chkdel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `barcode` varchar(255) DEFAULT NULL,
  `combination_amount` varchar(255) DEFAULT NULL,
  `combination_price` varchar(255) DEFAULT NULL,
  `combination_bonus` varchar(255) DEFAULT NULL,
  `onTop` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `level1` varchar(255) DEFAULT NULL,
  `level2` varchar(255) DEFAULT NULL,
  `level3` varchar(255) DEFAULT NULL,
  `level4` varchar(255) DEFAULT NULL,
  `level5` varchar(255) DEFAULT NULL,
  `cost` varchar(255) DEFAULT NULL,
  `updatetime` datetime DEFAULT NULL,
  `creator` varchar(255) DEFAULT NULL,
  `modifer` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`productID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------------
-- 新加坡 分類表 pro_classlist_sg
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_classlist_sg` (
  `classlistID` bigint(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `folderName` varchar(255) DEFAULT NULL,
  `classname` varchar(255) DEFAULT NULL,
  `classseries` varchar(255) DEFAULT NULL,
  `classmaster` bigint(16) UNSIGNED DEFAULT NULL,
  `chk_assembly` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `profile` longtext,
  `price` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `item` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `classordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `chkdel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `onTop` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `pic` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`classlistID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------------
-- 新加坡 產品表 pro_product_sg
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_product_sg` (
  `productID` bigint(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `color_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `size_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `qty_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `color` text,
  `size` text,
  `qty` text,
  `youtube` varchar(255) DEFAULT NULL,
  `weight` varchar(255) DEFAULT NULL,
  `stock` varchar(255) DEFAULT NULL,
  `chk_stock` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `classID` bigint(16) UNSIGNED DEFAULT NULL,
  `productname` longtext,
  `productseries` varchar(255) DEFAULT NULL,
  `providerseries` varchar(255) DEFAULT NULL,
  `bonus` bigint(16) UNSIGNED DEFAULT 0,
  `productsimpleprofile` text,
  `productprofile` longtext,
  `productprofile1` longtext,
  `productprofile2` longtext,
  `usermanual` varchar(255) DEFAULT NULL,
  `auction_startprice` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_unit` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_start_yy` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_start_mm` int(4) UNSIGNED DEFAULT NULL,
  `auction_start_dd` int(5) UNSIGNED DEFAULT NULL,
  `auction_end_yy` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_end_mm` int(4) UNSIGNED DEFAULT NULL,
  `auction_end_dd` int(5) UNSIGNED DEFAULT NULL,
  `auction_ship_price` bigint(16) UNSIGNED DEFAULT NULL,
  `marketprice` varchar(255) DEFAULT NULL,
  `memberprice` varchar(255) DEFAULT NULL,
  `providerprice` varchar(255) DEFAULT NULL,
  `bonusprice` varchar(255) DEFAULT NULL,
  `bonuspriceSel` varchar(255) DEFAULT NULL,
  `bonuspriceA` varchar(255) DEFAULT NULL,
  `bonuspriceB` varchar(255) DEFAULT NULL,
  `bonuspriceC` varchar(255) DEFAULT NULL,
  `bonuspriceA_percent` varchar(255) DEFAULT NULL,
  `bonuspriceA_Sel` varchar(255) DEFAULT NULL,
  `bonuspriceB_Plus` varchar(255) DEFAULT NULL,
  `chk_hot` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_auction` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_special` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_limit` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_assembly` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `product_s_gif` varchar(255) DEFAULT NULL,
  `product_s_1_gif` varchar(255) DEFAULT NULL,
  `product_s_2_gif` varchar(255) DEFAULT NULL,
  `product_l_gif` varchar(255) DEFAULT NULL,
  `product_large_gif` varchar(255) DEFAULT NULL,
  `product_special_gif` varchar(255) DEFAULT NULL,
  `productnum` bigint(16) UNSIGNED DEFAULT 0,
  `productordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `posttime` datetime DEFAULT NULL,
  `wholeseries` varchar(255) DEFAULT NULL,
  `limit_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `hot_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `special_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `factory_email` varchar(255) DEFAULT NULL,
  `click` bigint(24) UNSIGNED NOT NULL DEFAULT 0,
  `safenum` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `colorsize` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `letterSearch` varchar(255) DEFAULT NULL,
  `languageSearch` varchar(255) DEFAULT NULL,
  `shopNum` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `chkdel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `barcode` varchar(255) DEFAULT NULL,
  `combination_amount` varchar(255) DEFAULT NULL,
  `combination_price` varchar(255) DEFAULT NULL,
  `combination_bonus` varchar(255) DEFAULT NULL,
  `onTop` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `level1` varchar(255) DEFAULT NULL,
  `level2` varchar(255) DEFAULT NULL,
  `level3` varchar(255) DEFAULT NULL,
  `level4` varchar(255) DEFAULT NULL,
  `level5` varchar(255) DEFAULT NULL,
  `cost` varchar(255) DEFAULT NULL,
  `updatetime` datetime DEFAULT NULL,
  `creator` varchar(255) DEFAULT NULL,
  `modifer` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`productID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------------
-- 緬甸 分類表 pro_classlist_mm
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_classlist_mm` (
  `classlistID` bigint(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `folderName` varchar(255) DEFAULT NULL,
  `classname` varchar(255) DEFAULT NULL,
  `classseries` varchar(255) DEFAULT NULL,
  `classmaster` bigint(16) UNSIGNED DEFAULT NULL,
  `chk_assembly` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `profile` longtext,
  `price` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `item` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `classordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `chkdel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `onTop` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `pic` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`classlistID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------------
-- 緬甸 產品表 pro_product_mm
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS `pro_product_mm` (
  `productID` bigint(16) UNSIGNED NOT NULL AUTO_INCREMENT,
  `color_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `size_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `qty_on_off` int(3) UNSIGNED NOT NULL DEFAULT 0,
  `color` text,
  `size` text,
  `qty` text,
  `youtube` varchar(255) DEFAULT NULL,
  `weight` varchar(255) DEFAULT NULL,
  `stock` varchar(255) DEFAULT NULL,
  `chk_stock` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `classID` bigint(16) UNSIGNED DEFAULT NULL,
  `productname` longtext,
  `productseries` varchar(255) DEFAULT NULL,
  `providerseries` varchar(255) DEFAULT NULL,
  `bonus` bigint(16) UNSIGNED DEFAULT 0,
  `productsimpleprofile` text,
  `productprofile` longtext,
  `productprofile1` longtext,
  `productprofile2` longtext,
  `usermanual` varchar(255) DEFAULT NULL,
  `auction_startprice` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_unit` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_start_yy` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_start_mm` int(4) UNSIGNED DEFAULT NULL,
  `auction_start_dd` int(5) UNSIGNED DEFAULT NULL,
  `auction_end_yy` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_end_mm` int(4) UNSIGNED DEFAULT NULL,
  `auction_end_dd` int(5) UNSIGNED DEFAULT NULL,
  `auction_ship_price` bigint(16) UNSIGNED DEFAULT NULL,
  `marketprice` varchar(255) DEFAULT NULL,
  `memberprice` varchar(255) DEFAULT NULL,
  `providerprice` varchar(255) DEFAULT NULL,
  `bonusprice` varchar(255) DEFAULT NULL,
  `bonuspriceSel` varchar(255) DEFAULT NULL,
  `bonuspriceA` varchar(255) DEFAULT NULL,
  `bonuspriceB` varchar(255) DEFAULT NULL,
  `bonuspriceC` varchar(255) DEFAULT NULL,
  `bonuspriceA_percent` varchar(255) DEFAULT NULL,
  `bonuspriceA_Sel` varchar(255) DEFAULT NULL,
  `bonuspriceB_Plus` varchar(255) DEFAULT NULL,
  `chk_hot` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_auction` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_special` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_limit` tinyint(1) UNSIGNED DEFAULT 0,
  `chk_assembly` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `product_s_gif` varchar(255) DEFAULT NULL,
  `product_s_1_gif` varchar(255) DEFAULT NULL,
  `product_s_2_gif` varchar(255) DEFAULT NULL,
  `product_l_gif` varchar(255) DEFAULT NULL,
  `product_large_gif` varchar(255) DEFAULT NULL,
  `product_special_gif` varchar(255) DEFAULT NULL,
  `productnum` bigint(16) UNSIGNED DEFAULT 0,
  `productordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `posttime` datetime DEFAULT NULL,
  `wholeseries` varchar(255) DEFAULT NULL,
  `limit_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `auction_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `hot_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `special_ordernum` bigint(16) UNSIGNED DEFAULT NULL,
  `factory_email` varchar(255) DEFAULT NULL,
  `click` bigint(24) UNSIGNED NOT NULL DEFAULT 0,
  `safenum` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `colorsize` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `letterSearch` varchar(255) DEFAULT NULL,
  `languageSearch` varchar(255) DEFAULT NULL,
  `shopNum` bigint(16) UNSIGNED NOT NULL DEFAULT 0,
  `chkdel` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
  `barcode` varchar(255) DEFAULT NULL,
  `combination_amount` varchar(255) DEFAULT NULL,
  `combination_price` varchar(255) DEFAULT NULL,
  `combination_bonus` varchar(255) DEFAULT NULL,
  `onTop` tinyint(1) UNSIGNED NOT NULL DEFAULT 1,
  `level1` varchar(255) DEFAULT NULL,
  `level2` varchar(255) DEFAULT NULL,
  `level3` varchar(255) DEFAULT NULL,
  `level4` varchar(255) DEFAULT NULL,
  `level5` varchar(255) DEFAULT NULL,
  `cost` varchar(255) DEFAULT NULL,
  `updatetime` datetime DEFAULT NULL,
  `creator` varchar(255) DEFAULT NULL,
  `modifer` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`productID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
